[
project
]
name = "function-optimization-rag"
version = "0.1.0"
description = "Function optimization RAG application with separate embedding and chat endpoints"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "langchain>=0.2.0",
    "langchain-openai>=0.0.2",
    "openai>=1.3.0",
    "azure-search-documents>=11.4.0",
    "azure-identity>=1.12.0",
    "python-dotenv>=1.0.0",
    "tenacity>=8.2.2",
]

[
build-system
]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[
tool.uv
]
exclude = ["tests", "docs"]
